name: CI/CD Database Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MySQL client
      run: sudo apt-get install -y mysql-client

    - name: Debug environment variables
      run: |
        echo "MYSQL_HOST: $MYSQL_HOST"
        echo "MYSQL_USER: $MYSQL_USER"
        echo "MYSQLDB_NAME: $MYSQLDB_NAME"

    - name: Execute SQL scripts
      env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < schema_changes.sql
